# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  Joint1:
    has_velocity_limits: false
    max_velocity: 0.5
    has_acceleration_limits: false
    max_acceleration: 0.4
  Joint2:
    has_velocity_limits: false
    max_velocity: 0.8
    has_acceleration_limits: false
    max_acceleration: 1.0
  Joint_GripperBase:
    has_velocity_limits: false
    max_velocity: 0.05
    has_acceleration_limits: false
    max_acceleration: 0.05
  base_link1_to_link1:
    has_velocity_limits: false
    max_velocity: 0
    has_acceleration_limits: false
    max_acceleration: 0