rotary_table_v3:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50


  # Position Controllers ---------------------------------------
  rt_position_controller:
    type: effort_controllers/JointPositionController
    joint: rotary_table_joint
    pid: {p: 500.0, i: 2.0, d: 10.0}

