scara_and_rt:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

scara:
  joint_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints:
      - Joint1
      - Joint2
      - Joint_GripperBase

    gains:
      Joint1: {p: 5000.0, i: 20, d: 120, i_clamp: 0.0}
      Joint2: {p: 5000.0, i: 20, d: 120, i_clamp: 0.0}
      Joint_GripperBase: {p: 1000.0, i: 20, d: 40, i_clamp: 0.0}


    constraints:
      goal_time: 1
      Joint1:
        goal: 0.1
      Joint2:
        goal: 0.1
      Joint_GripperBase:
        goal: 0.1

rt:
    joint_trajectory_controller:
      type: effort_controllers/JointTrajectoryController
      joints:
        - base_link1_to_link1
      gains:
        base_link1_to_link1: {p: 1000.0, i: 20.0, d: 120, i_clamp: 0.0}
    constraints:
          goal_time: 2
          base_link1_to_link1:
            goal: 0.3





